# PROGRAMMING ASSIGNMENT 2

GREFALDEO, Lettice Hyacinth P. | 2ECE-C

### Problem 1 - Reproducible Normalization Problem

In [4]:
import numpy as np

np.random.seed(2112)
X = np.random.randint(10, 101, size=(5,5)) #create a 5x5 size array 

#state the variables needed to normalize the array 
Xmean = np.mean(X)
Xstd = np.std(X)

#normalize using the given formula 
X_normalized = (X-Xmean)/(Xstd)

#display necessary output 
print("X:\n", X)
print("\nX_normalized:\n", X_normalized)
print("\nMean:", np.mean(X_normalized))
print("Standard Deviation:", np.std(X_normalized))

#save
np.save("X_normalized.npy", X_normalized)

X:
 [[48 11 15 67 21]
 [11 41 13 66 24]
 [71 79 53 67 70]
 [77 35 91 19 96]
 [35 54 37 41 17]]

X_normalized:
 [[ 0.06340841 -1.36714726 -1.2124926   0.79801809 -0.98051059]
 [-1.36714726 -0.20723725 -1.28981993  0.75935442 -0.86451959]
 [ 0.95267275  1.26198209  0.25672675  0.79801809  0.91400909]
 [ 1.18465476 -0.43921926  1.72594609 -1.05783793  1.91926443]
 [-0.43921926  0.29539042 -0.36189192 -0.20723725 -1.13516526]]

Mean: 0.0
Standard Deviation: 0.9999999999999999


### Problem 2 - Cubes Divisible by 4 Problem

In [5]:
import numpy as np 

#create a 10x10 array
ndarray = np.arange(1, 101)

#cube each element of the array
C = ndarray**3
C = C.reshape(10, 10)
div_by_4 = C[C % 4 == 0] #filter the elements divisible by 4

#display the necessary output
print("Shape of C:", C.shape)
print("\nValues divisible by 4:\n", div_by_4)
print("\nNumber of elements:", div_by_4.size)

#save
np.save("div_by_4.npy", div_by_4)

Shape of C: (10, 10)

Values divisible by 4:
 [      8      64     216     512    1000    1728    2744    4096    5832
    8000   10648   13824   17576   21952   27000   32768   39304   46656
   54872   64000   74088   85184   97336  110592  125000  140608  157464
  175616  195112  216000  238328  262144  287496  314432  343000  373248
  405224  438976  474552  512000  551368  592704  636056  681472  729000
  778688  830584  884736  941192 1000000]

Number of elements: 50


### Problem 3 - Above-Mean Sqaures Problem

In [7]:
import numpy as np

#create a 6x6 array named S, with positive integers only
S = np.arange(1,37)**2 #for positive integers only
S = S.reshape(6,6)

#compute mean
S_mean = np.mean(S)

#filter the elements that it is above the mean
above_mean = S[S>S_mean]

#display the necessary output
print("S:\n", S)
print("\nMean:", S_mean)
print("\nAbove mean:\n", above_mean)
print("\nNumber of elements:", above_mean.size) #first element should be 484, last element should be 1296

#save the file
np.save("above_mean.npy", above_mean)

S:
 [[   1    4    9   16   25   36]
 [  49   64   81  100  121  144]
 [ 169  196  225  256  289  324]
 [ 361  400  441  484  529  576]
 [ 625  676  729  784  841  900]
 [ 961 1024 1089 1156 1225 1296]]

Mean: 450.1666666666667

Above mean:
 [ 484  529  576  625  676  729  784  841  900  961 1024 1089 1156 1225
 1296]

Number of elements: 15
